baseURL = 'https://whatthe.zip'
languageCode = 'en-us'
title = 'stoics'
theme= 'risotto' # https://github.com/joeroe/risotto
DefaultContentLanguage = "en"

[params]
noindex = false

[params.theme]
palette = "tender"

[params.about]
title = "@stoicszip"
description = "self-proclaimed mensa certfified linux enthusiast"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/stoicszip"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:stoics@tuta.com"

[menu]

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

